#default
spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      name: ${job.name:None}
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2